# Generated by Django 5.1.6 on 2025-07-10 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0002_product_blog_blogcomment_order_complaint_orderdetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AccountStock',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('stock_code', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Thông tin định dạng tài khoản: user|pass|email|otp')),
                ('is_sold', models.BooleanField(default=False)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='MMO.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
