# Generated by Django 5.1.6 on 2025-07-10 16:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0003_remove_product_available_quantity_order_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='MMO.voucher'),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='type',
            field=models.CharField(choices=[('deposit', 'Nạp tiền'), ('withdraw', 'Rút tiền'), ('refund', 'Hoàn tiền'), ('purchase', 'Thanh toán đơn hàng'), ('receive', 'Nhận tiền bán')], max_length=20),
        ),
        migrations.CreateModel(
            name='AccOrderDetail',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('acc_order_detail_code', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('content_delivered', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_details', to='MMO.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_order_details', to='MMO.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderDetail',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('service_order_detail_code', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('target_url', models.URLField(help_text='Link TikTok/YouTube/Instagram cần tăng tương tác')),
                ('quantity', models.IntegerField(help_text='Số lượng cần tăng, ví dụ: 1000 follow', validators=[django.core.validators.MinValueValidator(1)])),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại')], default='pending', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='MMO.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_order_details', to='MMO.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
