# Generated by Django 5.1.6 on 2025-07-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0005_remove_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accorderdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='serviceorderdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
