# Generated by Django 5.1.6 on 2025-07-11 14:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0006_accorderdetail_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='max_discount',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
