# Generated by Django 5.1.6 on 2025-07-11 14:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0007_remove_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='max_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
