# Generated by Django 5.1.6 on 2025-07-11 14:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0008_voucher_max_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accorderdetail',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acc_detail', to='MMO.order'),
        ),
        migrations.AlterField(
            model_name='serviceorderdetail',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_detail', to='MMO.order'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='max_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('30000'), max_digits=10),
        ),
    ]
