# Generated by Django 5.1.6 on 2025-07-11 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0009_alter_accorderdetail_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='buyer',
            field=models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
