# Generated by Django 5.1.6 on 2025-07-11 15:46

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0012_remove_blog_created_at_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Nội dung'),
        ),
    ]
