# Generated by Django 5.1.6 on 2025-07-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0013_alter_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
    ]
