# Generated by Django 5.1.6 on 2025-07-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0016_alter_complaint_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cccd',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
