# Generated by Django 5.1.6 on 2025-07-18 04:20

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0018_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='cccd',
        ),
        migrations.RemoveField(
            model_name='store',
            name='verified',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='favoriteproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('verification_code', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('cccd', models.CharField(max_length=12, unique=True)),
                ('front_id', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Ảnh CCCD mặt trước')),
                ('back_id', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Ảnh CCCD mặt sau')),
                ('portrait', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Ảnh chân dung')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Bị từ chối')], default='pending', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
