# Generated by Django 5.1.6 on 2025-07-18 04:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0019_remove_store_cccd_remove_store_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='evidence_image',
            new_name='evidence_image2',
        ),
        migrations.AddField(
            model_name='complaint',
            name='evidence_image1',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='evidence_image3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='evidence_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
