# Generated by Django 5.1.6 on 2025-07-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0021_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('seller', 'Người bán'), ('customer', 'Người mua')], default='customer', max_length=10),
        ),
    ]
