# Generated by Django 5.1.6 on 2025-08-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0027_alter_user_managers_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
