# Generated by Django 5.1.6 on 2025-08-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0029_alter_blog_category_bloglike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglike',
            name='id',
        ),
        migrations.AddField(
            model_name='bloglike',
            name='blog_like_code',
            field=models.CharField(default=1, editable=False, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
