# Generated by Django 5.1.6 on 2025-08-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0030_remove_bloglike_id_bloglike_blog_like_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='voucher',
            unique_together={('store', 'code')},
        ),
    ]
