# Generated by Django 5.1.6 on 2025-08-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0031_alter_voucher_code_alter_voucher_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Đang xử lý'), ('delivered', 'Đã giao'), ('complained', 'Bị khiếu nại'), ('refunded', 'Đã hoàn tiền'), ('completed', 'Hoàn thành'), ('cancel', 'Huỷ')], max_length=20),
        ),
    ]
