# Generated by Django 5.1.6 on 2025-08-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0032_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Đang xử lý'), ('delivered', 'Đã giao'), ('complained', 'Bị khiếu nại'), ('refunded', 'Đã hoàn tiền'), ('completed', 'Hoàn thành'), ('cancel', 'Huỷ')], default='processing', max_length=20),
        ),
    ]
