# Generated by Django 5.1.6 on 2025-08-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0033_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accorderdetail',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='serviceorderdetail',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
