# Generated by Django 5.1.6 on 2025-08-21 09:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0034_accorderdetail_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accorderdetail',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='accorderdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1000000000'))]),
        ),
        migrations.AlterField(
            model_name='serviceorderdetail',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='serviceorderdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_percent',
            field=models.DecimalField(decimal_places=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='max_discount',
            field=models.DecimalField(decimal_places=0, default=Decimal('30000'), max_digits=10),
        ),
    ]
