# Generated by Django 5.1.6 on 2025-08-21 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0035_alter_accorderdetail_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='MMO.order'),
            preserve_default=False,
        ),
    ]
