# Generated by Django 5.1.6 on 2025-08-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0036_review_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='complaint',
            unique_together={('buyer', 'order')},
        ),
    ]
