# Generated by Django 5.1.6 on 2025-08-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0037_alter_complaint_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='decision',
            field=models.CharField(blank=True, choices=[('pending', 'Đang xem xét'), ('refund', 'Hoàn tiền người mua'), ('release', 'Trả tiền cho người bán'), ('negotiate', 'Yêu cầu thương lượng lại')], default='pending', max_length=20, null=True),
        ),
    ]
