# Generated by Django 5.1.6 on 2025-08-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0038_alter_complaint_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='evidence_video',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
