# Generated by Django 5.1.6 on 2025-08-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0039_alter_complaint_evidence_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='evidence_video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
