# Generated by Django 5.1.6 on 2025-08-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0040_alter_complaint_evidence_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='evidence_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
