# Generated by Django 5.1.6 on 2025-08-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0041_alter_complaint_evidence_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='evidence_video',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
