# Generated by Django 5.1.6 on 2025-08-30 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0042_alter_complaint_evidence_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deposit_code', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('transaction_code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('confirmed', 'Đã xác nhận'), ('rejected', 'Bị từ chối')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
