# Generated by Django 5.1.6 on 2025-08-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MMO', '0044_withdrawrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawrequest',
            name='note',
        ),
    ]
